
name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  DEV_TARBALL_VARIANT: _usrmerge
  ROOTFS_URL: "https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
  OTA_CHANNEL: "20.04/arm64/android9plus/stable"
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - id: Build Kernel
      - uses: actions/checkout@v3
      - name: Build
        run: | 
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          sudo wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
          sudo chmod +x /usr/bin/mkbootimg
          git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools build
          sudo -s ./build/build.sh
         
      - name: bootimg
        uses: actions/upload-artifact@master
        with:
          name: bootimg
          path: out/*
  
      - id: Deploying-DEV
      - name: deploy-devel
        run: |
            sudo apt update
            sudo apt install -y git img2simg jq sudo wget xz-utils
            sudo -s git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools build
            DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
            sudo -s ./build/prepare-fake-ota.sh out/device_${DEVICE}${DEV_TARBALL_VARIANT}.tar.xz ota
            mkdir -p out
            sudo -s ./build/system-image-from-ota.sh ota/ubuntu_command out
    
      - name: upload devimg
        uses: actions/upload-artifact@master
        with:
            name: ubuntuimg
            path: |
               out/boot.img
               out/system.img
